### ISSUE TITLE
Getting error EOF occurred in violation of protocol (_ssl.c:1123) slack-app

### ISSUE THREAD

**Issue by vv-grinko** [slackapi/bolt-python#227]
I have this error after launsh lesson https://slack.dev/bolt-python/tutorial/getting-started
I'm working behide a proxy server.

### Reproducible in:

```bash
(.venv) PS C:\first-bolt-app\.venv> py -3 app.py
Traceback (most recent call last):
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1123)
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "C:\first-bolt-app\.venv\app.py", line 5, in <module>
    app = App(
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\site-packages\slack_bolt\app\app.py", line 239, in __init__
    self._init_middleware_list(
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\site-packages\slack_bolt\app\app.py", line 256, in _init_middleware_list
    auth_test_result = self._client.auth_test(token=self._token)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\site-packages\slack_sdk\web\client.py", line 765, in auth_test
    return self.api_call("auth.test", json=kwargs)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\site-packages\slack_sdk\web\base_client.py", line 128, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\site-packages\slack_sdk\web\base_client.py", line 164, in _sync_send
    return self._urllib_api_call(
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\site-packages\slack_sdk\web\base_client.py", line 275, in _urllib_api_call
    response = self._perform_urllib_http_request(url=url, args=request_args)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\site-packages\slack_sdk\web\base_client.py", line 423, in _perform_urllib_http_request
    raise err
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\site-packages\slack_sdk\web\base_client.py", line 397, in _perform_urllib_http_request
    resp = urlopen(  # skipcq: BAN-B310
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\vvgrink1\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1123)>
```

#### The Slack SDK version

```
(.venv) PS C:\first-bolt-app\.venv> pip list
Package         Version
--------------- -------
cffi            1.14.4
cryptography    3.3.1
ndg-httpsclient 0.5.1
pip             20.2.3
pyasn1          0.4.8
pycparser       2.20
pyOpenSSL       20.0.1
setuptools      49.2.1
six             1.15.0
slack-bolt      1.2.3
slack-sdk       3.2.1
```

#### Python runtime version

Python 3.9.1

#### OS info

(Windows 10

#### Steps to reproduce:

```
import os
from slack_bolt import App
app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)
if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))
```

### Expected result:

start application

### Actual result:

Getting error urlopen error EOF occurred in violation of protocol (_ssl.c:1123)

**Comment by seratch** [comment]
@vv-grinko 
>I'm working behide a proxy server.

You can set the proxy url using this option. Can you try this out?

```python
import os
from slack_bolt import App
from slack_sdk.web import WebClient

# Enable your Web API client to go through the proxy
proxy_wired_client = WebClient(
    token=os.environ.get("SLACK_BOT_TOKEN"),
    proxy="your own proxy URL",
)

app = App(
    client=proxy_wired_client,
    signing_secret=os.environ.get("SLACK_SIGNING_SECRET")
)
if __name__ == "__main__":
    app.start(port=int(os.environ.get("PORT", 3000)))
```

**Comment by vv-grinko** [comment]
> ```python
> proxy=
> ```

![image](https://user-images.githubusercontent.com/65661924/106351326-aed60e80-62ec-11eb-8a2b-f6f16dcf1eb2.png)
There is no such variable

**Comment by seratch** [comment]
As my code snippet shows, it's an argument in the `WebClient` constructor. Create a `WebClient` instance with your proxy url and pass it to `App` constructor.

**Comment by vv-grinko** [comment]
> As my code snippet shows, it's an argument in the `WebClient` constructor. Create a `WebClient` instance with your proxy url and pass it to `App` constructor.

That's works! Thank you!

**Comment by MerreM** [comment]
I'm seeing this running a flask app on lambda - but not with the old SDK, is this expected?
