### ISSUE TITLE
Add a default attribute for selected_options for ViewStateValue

### ISSUE THREAD

**Issue by scott-shields-github** [slackapi/bolt-python#279]
Having a default attribute for selected_options would allow consistency with the other attributes available. As it is now, if a ViewStateValue object is created with an empty list for selected_options (ex. checkbox) no attribute will be created, leading to an AttributeError when accessed.

#### The `slack_bolt` version

`slack-bolt==1.4.4`

#### Python runtime version

`Python 3.8.3`

#### OS info

```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

```
>>> d = {"selected_options": []}
>>> v = ViewStateValue(**d)
>>> v
<slack_sdk.ViewStateValue>
>>> v.to_dict()
{}
>>> v.selected_options
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ViewStateValue' object has no attribute 'selected_options'
```

### Expected result:

It would be nice to have a default of `None`

### Actual result:

```
>>> d = {"selected_options": []}
>>> v = ViewStateValue(**d)
>>> v
<slack_sdk.ViewStateValue>
>>> v.to_dict()
{}
>>> v.selected_options
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ViewStateValue' object has no attribute 'selected_options'
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by scott-shields-github** [comment]
Wrong repo 👎 :)
