### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'send' when using modal to collect data

### ISSUE THREAD

**Issue by RachelDong** [slackapi/bolt-python#461]
Hello,

I'm using slack modal to collect some data from user, the modal openned for user is like
<img src="https://user-images.githubusercontent.com/34002808/132354218-40d22017-04c4-408b-83b7-465286d5df90.png" width=300 />

The number of comment-department pairs showed in the modal depends on some internal logic. 
The modal can be submitted successfully when there are 3 such comment-department pairs, but when there are more than 3 pairs submitted, the following error occurs:
```
on_error invoked (session id: f429bc62-393e-414a-bc43-8570b95a075b, error: error, message: unpack requires a buffer of 2 
bytes)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 284, in run_until_completion
    ] = _receive_messages(
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 214, in _receive_messages
    return _fetch_messages(
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 279, in _fetch_messages 
    current_data_length = struct.unpack("!H", bytes(remaining_bytes[2:10]))[0]
struct.error: unpack requires a buffer of 2 bytes
Received an unsupported data frame ......
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 355, in run_until_completion
    self.pong(data)
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 213, in pong
    self.sock.send(data)
AttributeError: 'NoneType' object has no attribute 'send'
on_error invoked (session id: bb83db5b-9fa3-4880-9fb5-e238a4b7cb75, error: error, message: unpack requires a buffer of 2 
bytes)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 284, in run_until_completion
    ] = _receive_messages(
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 214, in _receive_messages
    return _fetch_messages(
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/internals.py", line 279, in _fetch_messages 
    current_data_length = struct.unpack("!H", bytes(remaining_bytes[2:10]))[0]
struct.error: unpack requires a buffer of 2 bytes
Received an unsupported data frame ......
on_error invoked (session id: bb83db5b-9fa3-4880-9fb5-e238a4b7cb75, error: AttributeError, message: 'NoneType' object has no attribute 'send')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 355, in run_until_completion
    self.pong(data)
  File "/usr/local/lib/python3.9/site-packages/slack_sdk/socket_mode/builtin/connection.py", line 213, in pong
    self.sock.send(data)
AttributeError: 'NoneType' object has no attribute 'send'
```

I have no idea why I got this error, and this error only occurs when there are more than 3 comment-department pairs are submitted. Can anyone help me? Thanks a lot.

**Comment by filmaj** [comment]
@RachelDong can you share your code that generates the modal and the submission handler?

**Comment by RachelDong** [comment]
```
# listen to the button click action
@app.action("actionId-add-info")
def open_modal(body, logger,ack):
    # Acknowledge shortcut request
    ack()
    view = {"callback_id":"add_info_view",
            "title": {
                "type": "plain_text",
                "text": "My App",
                "emoji": True
            },
            "submit": {
                "type": "plain_text",
                "text": "Submit",
                "emoji": True
            },
            "type": "modal",
            "close": {
                "type": "plain_text",
                "text": "Cancel",
                "emoji": True
            },
            "blocks": []}
    # code to calculate how many comment-department pairs should be showed
    # count = number of comment-department pairs should be showed
    for i in range(count):
        template1 = {"type": "input",
                    "element": {
                        "type": "plain_text_input",
                        "action_id": "plain_text_input-action"
                    },
                    "label": {
                        "type": "plain_text",
                        "text": "Comment1",
                        "emoji": True
                    }
                }
        template2 = {"type": "input",
                        "element": {
                            "type": "static_select",
                            "placeholder": {
                                "type": "plain_text",
                                "text": "Select an item",
                                "emoji": True
                            },
                            "options": [
                                {
                                    "text": {
                                        "type": "plain_text",
                                        "text": "*this is plain_text text*",
                                        "emoji": True
                                    },
                                    "value": "value-0"
                                },
                                {
                                    "text": {
                                        "type": "plain_text",
                                        "text": "*this is plain_text text*",
                                        "emoji": True
                                    },
                                    "value": "value-1"
                                },
                                {
                                    "text": {
                                        "type": "plain_text",
                                        "text": "*this is plain_text text*",
                                        "emoji": True
                                    },
                                    "value": "value-2"
                                }
                            ],
                            "action_id": "static_select-action"
                        },
                        "label": {
                            "type": "plain_text",
                            "text": "Department1",
                            "emoji": True
                        }
                    }
        view['blocks'].append(template1)
        view['blocks'].append(template2)
	slack_client.views_open(trigger_id=body['trigger_id'],view=view)

# when the view is submitted
@app.view("add_info_view")
def handle_submission(ack, body, client, view, logger,say):
    ack()
    say("info received")
```

Actually I did nothing in the submission handler, the error occurs when I click the 'submit' button on the modal, on the slack UI side, the modal didn't close and prompted:
![图片](https://user-images.githubusercontent.com/34002808/132371245-f9198e29-00d3-48a4-b97f-37ba6bb32155.png)
on the terminal side, the above error was thrown.

By the way, I'm using socket mode, and in the main function, the SocketModeHandler is running along with a flask app with the multi-processing method.

**Comment by seratch** [comment]
@RachelDong Thanks for sharing this. The `NoneType` errors can be improved but I think the errors are results, not the cause of your issue. It seems that your app's Socket Mode connection (=WebSocket connection) is inactive for some reason in this scenario. As the connection is not working, the modal data submission failed on the end-user side.

I'm still not sure about the reproduction steps of this situation but if you find some conditions causing this, sharing the details would be greatly appreciated.

**Comment by seratch** [comment]
By the way, if you still have the `say("info received")` in the `@app.view` listener, the error you shared can arise.

```
ERROR:slack_bolt.App:Failed to run listener function (error: say without channel_id here is unsupported)
Traceback (most recent call last):
  File "/Users/ksera/github/bolt-python/slack_bolt/listener/thread_runner.py", line 112, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/ksera/github/bolt-python/slack_bolt/listener/custom_listener.py", line 49, in run_ack_function
    return self.ack_function(
  File "/Users/ksera/github/bolt-python/examples/socket_mode.py", line 102, in handle_submission
    say("info received")
  File "/Users/ksera/github/bolt-python/slack_bolt/context/say/say.py", line 58, in __call__
    raise ValueError("say without channel_id here is unsupported")
ValueError: say without channel_id here is unsupported
WARNING:slack_bolt.App:handle_submission didn't call ack()
WARNING:slack_bolt.App:Unhandled request ({'type': 'view_submission', 'view': {'type': 'modal', 'callback_id': 'add_info_view'}})
```

<img width="300" src="https://user-images.githubusercontent.com/19658/132797200-cba1006c-68c4-4eca-be16-afd10a94485a.png">


Perhaps, this is not related to the main part of your question, though.

**Comment by seratch** [comment]
@RachelDong Thanks again for reporting this issue. 

While investigating further, I found rooms for improvements in the underlying SocketModeClient SDK. **While reconnecting to the WebSocket server for some reason**, sending messages can fail or be delayed. This misbehavior can result in modal data submission failures, timeout errors of end-user interactions. https://github.com/slackapi/python-slack-sdk/pull/1114 improves the SDK internals to deal with this situation properly. 

The `self.sock`'s `NoneType` errors can arise in this scenario. Thus, I'm expecting that this improvement can be helpful for your use cases too.

**Comment by RachelDong** [comment]
@seratch Really thank you for the reply. I suspect one thing maybe relating to the issue is that actually I have more than 200 options in the "Department" field, and when it repeats, say more than 3 times, the message data which will be transported by the websocket server is so large that the server actually cannot send the message.

**Comment by seratch** [comment]
@RachelDong We generally don't recommend loading a large number of options for better end-user experience (the loading can be slow with many options). Aside from the error that your app experienced, I would suggest using external data source for this use case. Refer to the following documents for more details. Using this feature is simple. Having `external_select` / `multi_external_select` blocks in your modal and handles the options loading request by corresponding `@app.options` listener.

* https://api.slack.com/reference/block-kit/block-elements#external_multi_select
* https://slack.dev/bolt-python/concepts#options

I hope this was helpful.

**Comment by RachelDong** [comment]
That's really nice:) thanks a lot.
