### ISSUE TITLE
`slack_bolt` socket mode connection eventually fails at `connect()` 

### ISSUE THREAD

**Issue by 0bprashanthc** [slackapi/bolt-python#470]
I am running a slack application in socket mode. While initiating the slack app websocket connection using `connect()`, I am handling an error event on the app by passing the error handler to `SocketModeHandler`. I now see the socket connections are inconsistent and eventually fail with below log messages.

#### The `slack_bolt` version

```
slack-bolt==1.7.0
slack-sdk==3.8.0
```

#### Python runtime version

```
Python 3.6.8
```

#### OS info

```
$ uname -a
Linux dev-10-178-5-101 3.10.0-1160.15.2.el7.x86_64 #1 SMP Thu Jan 21 16:15:07 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

#### Steps to reproduce:

1. I am using below code to initialise slack app in socket-mode.
```
    def reinit_handle(self, webSocketApp, error):
        log.info("re-init slack bot with new socket connection")
        try:
            webSocketApp.close()
        except:
            log.error("unable to close existing socket connections")
        finally:
            self.slack_init()

    def slack_init(self):
        log.info("slack socket server init")
        host,port = env["PROXY"].split(":")
        try:
            while True and (self.sapp is not None):
                app_handle = SocketModeHandler(self.sapp, env["SLACK_APP_TOKEN"], http_proxy_host=host, http_proxy_port=port, proxy_type='http')
                app_handle.client.on_error_listeners.append(self.reinit_handle)
                app_handle.connect()
                Event().wait(timeout=500)
        except Exception as e:
            log.error("unable to init slack app: ",e)

    o.slack_init()
```

### Actual result:

The connections seems to be working fine with below logs:
```
2021-09-16 23:14:20,895:INFO:ombot.routes:slack_init:slack socket server init
2021-09-16 23:14:20,969:INFO:slack_bolt.App:_monitor_current_session:The session seems to be already closed. Going to reconnect...
2021-09-16 23:14:20,969:INFO:slack_bolt.App:connect:A new session has been established
2021-09-16 23:14:21,396:INFO:slack_bolt.App:_run_current_session:Starting to receive messages from a new connection
```
However, soon after few minutes I get below log messages:
```
2021-09-17 01:46:42,806:INFO:slack_bolt.App:_monitor_current_session:The session seems to be already closed. Going to reconnect...
2021-09-17 01:46:47,166:ERROR:slack_bolt.App:on_error:on_error invoked (error: WebSocketBadStatusException, message: Handshake status 408 Request Timeout)
2021-09-17 01:46:47,166:INFO:ombot.routes:reinit_handle:re-init slack bot with new socket connection
2021-09-17 01:46:47,166:INFO:ombot.routes:slack_init:slack socket server init
```
As you can see above, my slack error handler `reinit_handle` is kicked in to restart the slack app with new socket connection. This seems to work fine as well. However after few hours the `reinit_handle` when trying to recover with a new connection, it fails with below log messages:
```
2021-09-17 03:50:35,311:WARNING:websocket:warning:send_ping routine terminated: socket is already closed.
2021-09-17 03:48:45,917:INFO:slack_bolt.App:_monitor_current_session:The session seems to be already closed. Going to reconnect...
2021-09-17 03:50:44,631:ERROR:slack_bolt.App:on_error:on_error invoked (error: WebSocketConnectionClosedException, message: Connection to remote host was lost.)
2021-09-17 03:50:52,212:ERROR:slack_bolt.App:on_error:on_error invoked (error: WebSocketConnectionClosedException, message: Connection to remote host was lost.)
2021-09-17 03:50:52,216:WARNING:websocket:warning:send_ping routine terminated: [Errno 9] Bad file descriptor
2021-09-17 03:52:12,110:ERROR:slack_bolt.App:on_error:on_error invoked (error: WebSocketConnectionClosedException, message: Connection to remote host was lost.)
2021-09-17 03:52:19,008:WARNING:websocket:warning:send_ping routine terminated: socket is already closed.
2021-09-17 03:52:30,218:WARNING:websocket:warning:send_ping routine terminated: [Errno 32] Broken pipe
2021-09-17 03:52:30,913:ERROR:slack_bolt.App:on_error:on_error invoked (error: BrokenPipeError, message: [Errno 32] Broken pipe)
2021-09-17 03:52:32,037:ERROR:slack_bolt.App:on_error:on_error invoked (error: WebSocketConnectionClosedException, message: Connection to remote host was lost.)
2021-09-17 03:55:20,419:ERROR:slack_bolt.App:on_error:on_error invoked (error: BrokenPipeError, message: [Errno 32] Broken pipe)
2021-09-17 03:55:21,291:ERROR:slack_bolt.App:on_error:on_error invoked (error: WebSocketConnectionClosedException, message: Connection to remote host was lost.)
2021-09-17 03:55:22,611:WARNING:websocket:warning:send_ping routine terminated: [SSL: BAD_LENGTH] bad length (_ssl.c:2483)
```

post to this, when `reinit_handle` continuously tries to recover from the above errors it gets into even bad state with below logs:
```
2021-09-17 04:05:44,106:INFO:ombot.routes:reinit_handle:re-init slack bot with new socket connection
2021-09-17 04:04:22,604:WARNING:websocket:warning:send_ping routine terminated: [Errno 32] Broken pipe
2021-09-17 04:04:23,414:ERROR:slack_bolt.App:on_error:on_error invoked (error: BrokenPipeError, message: [Errno 32] Broken pipe)
2021-09-17 04:04:23,419:ERROR:slack_bolt.App:on_error:on_error invoked (error: BrokenPipeError, message: [Errno 32] Broken pipe)
2021-09-17 04:04:24,009:WARNING:websocket:warning:send_ping routine terminated: [Errno 32] Broken pipe
2021-09-17 04:04:25,111:ERROR:slack_bolt.App:_perform_urllib_http_request:Failed to send a request to Slack API server: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>
--- Logging error ---
Traceback (most recent call last):
  File "/bb/libexec/ombot/python/lib/python39.zip/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/bb/libexec/ombot/python/lib/python39.zip/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/bb/libexec/ombot/python/lib/python39.zip/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/bb/libexec/ombot/python/lib/python39.zip/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/bb/libexec/ombot/python/lib/python39.zip/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/bb/libexec/ombot/python/lib/python39.zip/http/client.py", line 952, in send
    self.connect()
  File "/bb/libexec/ombot/python/lib/python39.zip/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/bb/libexec/ombot/python/lib/python39.zip/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/bb/libexec/ombot/python/lib/python39.zip/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/bb/libexec/ombot/python/lib/python39.zip/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bb/libexec/ombot/dependencies/site-packages/ombot/routes.py", line 92, in slack_init
    app_handle.connect()
  File "/bb/libexec/ombot/dependencies/site-packages/slack_bolt/adapter/socket_mode/base_handler.py", line 31, in connect
    self.client.connect()
  File "/bb/libexec/ombot/dependencies/site-packages/slack_sdk/socket_mode/websocket_client/__init__.py", line 188, in connect
    self.wss_uri = self.issue_new_wss_url()
  File "/bb/libexec/ombot/dependencies/site-packages/slack_sdk/socket_mode/client.py", line 48, in issue_new_wss_url
    response = self.web_client.apps_connections_open(app_token=self.app_token)
  File "/bb/libexec/ombot/dependencies/site-packages/slack_sdk/web/client.py", line 930, in apps_connections_open
    return self.api_call("apps.connections.open", http_verb="POST", params=kwargs)
  File "/bb/libexec/ombot/dependencies/site-packages/slack_sdk/web/base_client.py", line 135, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/bb/libexec/ombot/dependencies/site-packages/slack_sdk/web/base_client.py", line 171, in _sync_send
    return self._urllib_api_call(
  File "/bb/libexec/ombot/dependencies/site-packages/slack_sdk/web/base_client.py", line 284, in _urllib_api_call
    response = self._perform_urllib_http_request(url=url, args=request_args)
  File "/bb/libexec/ombot/dependencies/site-packages/slack_sdk/web/base_client.py", line 437, in _perform_urllib_http_request
    raise err
  File "/bb/libexec/ombot/dependencies/site-packages/slack_sdk/web/base_client.py", line 409, in _perform_urllib_http_request
    resp = opener.open(req, timeout=self.timeout)  # skipcq: BAN-B310
  File "/bb/libexec/ombot/python/lib/python39.zip/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/bb/libexec/ombot/python/lib/python39.zip/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/bb/libexec/ombot/python/lib/python39.zip/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/bb/libexec/ombot/python/lib/python39.zip/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/bb/libexec/ombot/python/lib/python39.zip/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1129)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bb/libexec/ombot/python/lib/python39.zip/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/bb/libexec/ombot/python/lib/python39.zip/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/bb/libexec/ombot/python/lib/python39.zip/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/bb/libexec/ombot/python/lib/python39.zip/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/bb/libexec/ombot/python/lib/python39.zip/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/bb/libexec/ombot/python/lib/python39.zip/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/bb/libexec/ombot/dependencies/site-packages/ombot/__main__.py", line 3, in <module>
    Factory().get_application()
  File "/bb/libexec/ombot/dependencies/site-packages/ombot/routes.py", line 110, in get_application
    self.slack_init()
  File "/bb/libexec/ombot/dependencies/site-packages/ombot/routes.py", line 95, in slack_init
    log.error("unable to init slack app: ",e)
Message: 'unable to init slack app: '
Arguments: (URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')),)
```

I am not sure if this is an issue with my implementation or an issue with `slack_bolt` or `slack_sdk`. can someone help me understand more about what's going on here ? 
Attaching full length log file to the issue:
[logs-from-app-in-slackbot--slackbot-beta--apprel-7f7b9c7458-gvb7b.txt](https://github.com/slackapi/bolt-python/files/7198734/logs-from-app-in-slackbot--slackbot-beta--apprel-7f7b9c7458-gvb7b.txt)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @0bprashanthc, thanks for writing in and sharing the details of your app's situation (that's really helpful to understand the issue!).

According to the attached log, your WebSocket connection is not stable from the beginning. The log shows `_monitor_current_session:The session seems to be already closed. Going to reconnect...` every 8-9 minutes. This is not a common situation. This log can show up only when the underlying WebSocket client (it seems that you're using websocket_client PyPI package based one) is unable to keep a connection with the Slack server-side (the reasons are socket closed, ping-pong communication failures for a while, etc.) or intermittent issue occurs in the environment. In a normal scenario, every a few hours, your Socket Mode connection will be renewed under the hood.

I have a few suggestions for you:

* I'm guessing that your proxy environment may have some configuration related to the 8-9 minute timeframe. Can you check the internal information if possible?
* Setting `trace_enabled` to True may help you see what's happening to your app. You can pass the option in the constructor: https://github.com/slackapi/bolt-python/blob/v1.9.1/slack_bolt/adapter/socket_mode/websocket_client/__init__.py#L34
* To narrow the issue down, running a simpler WebSocket example application (no need to connect to Slack; just trying to keep an outgoing WebSocket connection with detailed logs) in the same environment may help figuring out the affecting factors.

The following may not be relevant to the issue here but for improvements:

* When recreating a Socket Mode client, you can call `SocketModeHandler#close()` method (in your code `app_handle.close()`) to safely shutdown the existing Socket Mode client.
* Please upgrade to `slack-sdk` to the latest (v3.11.1 as of today) -- particularly, in v3.11.0, we've applied improvements to Socket Mode client internals. I don't think those changes can eliminate your issue but you may see some difference.

I hope this helps! If we identify rooms for improvement on this SDK side, we will quickly fix/improve them.

**Comment by 0bprashanthc** [comment]
Hi @seratch, thanks for responding real quick!

1. `_monitor_current_session:The session seems to be already closed. Going to reconnect...` this log appears every 8-9 minutes as I am using `Event().wait(timeout=500)` after `app_handle.connect()` in the above implemented socket init method. Can you confirm if this is a problem? or let me know the right way to use `connect()` as I don't want to use `start()`
2. I enabled trace and also am closing the app handle this time during re-inits. Also I updated slack_sdk to latest. Can we keep this issue opened for few more days and I can update with my observations here?

Let me know, thanks again!

**Comment by seratch** [comment]
@0bprashanthc 

>this log appears every 8-9 minutes as I am using Event().wait(timeout=500) after app_handle.connect() 

Ah, I see. That makes sense. This is why your app starts to get connectivity issues afterwards. Your app tries to create more and more connections in the app (as you don't call disconnect/close method for each). We don't recommend doing this way.

>let me know the right way to use connect() as I don't want to use start()

The `connect()` method starts a new Socket Mode connection in a different thread and also maintain its connection for you under the hood. Thus, all you need to do are:
* Create a `SocketModeHandler` instance and keep the reference to the object as part of your main code
* Call `SocketModeHandler#connect()` and you don't need to do anything further
* If you want to gracefully shutdown your app when terminating the process, you can call the saved `SocketModeHandler` instance's `close()` method to clean up the background threads

Your code should be much simpler! I think that now everything is clear but let us know if you need more help here.

**Comment by 0bprashanthc** [comment]
@seratch 

sounds good, so here is how my init function looks like:
```
    def slack_init(self):
        log.info("slack socket server init")
        host,port = env["PROXY"].split(":")
        try:
            while True and (self.sapp is not None):
                self.app_handle = SocketModeHandler(self.sapp, env["SLACK_APP_TOKEN"], http_proxy_host=host, http_proxy_port=port, proxy_type='http', trace_enabled=True)
                self.app_handle.client.on_error_listeners.append(self.reinit_handle)
                self.app_handle.connect()
                Event().wait()
        except Exception as e:
            log.error("unable to init slack app: ",e)
```

Do you think that `Event().wait()` is needed in this code?

**Comment by seratch** [comment]
@0bprashanthc 
>Do you think that Event().wait() is needed in this code?

If you would like to do so, you can use the `SockeModeHandler#start()` method instead. 

Also, I don't see any necessity to have the while loop `while True and (self.sapp is not None):` here. You can rely on the `SockeModeHandler`'s internals to manage the underlying connections. No need to have your own custom logic.

**Comment by 0bprashanthc** [comment]
@seratch thanks for your help, I think your suggestions improved my app experience from sloppy connections. I am closing this issue now.
