### ISSUE TITLE
Failed to send a request to Slack API server: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

### ISSUE THREAD

**Issue by descaptico** [slackapi/bolt-python#673]
(Describe your issue and goal here)
I am following this tutorial: https://api.slack.com/start/building/bolt-python
But I am always getting below error on running the `python app.py` command

[Failed to send a request to Slack API server: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
Failed to send a request to Slack API server: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/delacroix/Desktop/first-bolt-app/app.py", line 15, in <module>
    app = App(token=SLACK_BOT_TOKEN, name="Joke Bot")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_bolt/app/app.py", line 344, in __init__
    self._init_middleware_list(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_bolt/app/app.py", line 381, in _init_middleware_list
    auth_test_result = self._client.auth_test(token=self._token)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_sdk/web/client.py", line 1526, in auth_test
    return self.api_call("auth.test", params=kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 294, in _urllib_api_call
    response = self._perform_urllib_http_request(url=url, args=request_args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 473, in _perform_urllib_http_request
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 397, in _perform_urllib_http_request
    resp = self._perform_urllib_http_request_internal(url, req)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/slack_sdk/web/base_client.py", line 504, in _perform_urllib_http_request_internal
    resp = urlopen(req, context=self.ssl, timeout=self.timeout)  # skipcq: BAN-B310
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>](url)

### Reproducible in:

ProductName:	macOS
ProductVersion:	11.6.4
BuildVersion:	20G417
Darwin Kernel Version 20.6.0: Wed Jan 12 22:22:42 PST 2022; root:xnu-7195.141.19~2/RELEASE_X86_64

#### The `slack_bolt` version

slack-bolt==1.14.0
slack-sdk==3.17.2

#### Python runtime version
Python 3.10.5

#### Steps to reproduce:

Gist: https://gist.github.com/descaptico/64bf58b32de6c36cdaf48199a2a42f86

1. Just run the code in the above gist with the `python3 app.py` command gives this error
2.
3.

### Expected result:

(Tell what you expected to happen)

The bolt app should start running 

### Actual result:
I get an error as listed above

(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by RichieRunner** [comment]
> The issue was with my python installation. I went to the `applications/ python`folder and clicked on the `install certificate command` it got fixed after that.

What is a "install certificate command"? What command is there in the python lib in your venv?

**Comment by TobiahRex** [comment]
Adding specificity to @descaptico answer for Mac: 🙏
`/Applications/Python\ 3.*/Install\ Certificates.command`
