### ISSUE TITLE
trigger_id sometimes expires while using shortcut

### ISSUE THREAD

**Issue by lucafx** [slackapi/bolt-python#772]
### Description:
Hello everybody,

I got the below errors intermittently in my code, this is when it opens correctly the modal:

```
2022-11-21,14:43:02.393 DEBUG {client} [_on_message] on_message invoked: (message: {"envelope_id":"8bfbc62c-5d2e-4820-b0e7-058f667c77ff","payload":{"type":"shortcut","token":"ZtSxK1RA3UTWN9tJ9TljKNhm","action_ts":"1669038179.572326","team":{"id":"T049Y9BDDK5","domain":"testincidento-aoi8763"},"user":{"id":"U04AN3EJ73J","username":"lucalocasto","team_id":"T049Y9BDDK5"},"is_enterprise_install":false,"enterprise":null,"callback_id":"open_incident_jira","trigger_id":"4426479715376.4338317455651.e9188f6598536b94cc1eecbc714a2c64"},"type":"interactive","accepts_response_payload":false})
2022-11-21,14:43:02.394 DEBUG {client} [enqueue_message] A new message enqueued (current queue size: 1)
2022-11-21,14:43:02.394 DEBUG {client} [process_message] A message dequeued (current queue size: 0)
2022-11-21,14:43:02.394 DEBUG {client} [run_message_listeners] Message processing started (type: interactive, envelope_id: 8bfbc62c-5d2e-4820-b0e7-058f667c77ff)
2022-11-21,14:43:02.395 DEBUG {app} [dispatch] Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
2022-11-21,14:43:02.395 DEBUG {app} [dispatch] Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
2022-11-21,14:43:02.395 DEBUG {app} [dispatch] Applying slack_bolt.middleware.authorization.single_team_authorization.SingleTeamAuthorization
2022-11-21,14:43:02.395 DEBUG {app} [dispatch] Applying slack_bolt.middleware.ignoring_self_events.ignoring_self_events.IgnoringSelfEvents
2022-11-21,14:43:02.395 DEBUG {app} [dispatch] Applying slack_bolt.middleware.url_verification.url_verification.UrlVerification
2022-11-21,14:43:02.395 DEBUG {app} [dispatch] Checking listener: open_modal_step1 ...
2022-11-21,14:43:02.396 DEBUG {app} [dispatch] Running listener: open_modal_step1 ...
2022-11-21,14:43:02.396 DEBUG {base_client} [_urllib_api_call] Sending a request - url: https://www.slack.com/api/views.open, query_params: {}, body_params: {}, files: {}, json_body: {'trigger_id': '4426479715376.4338317455651.e9188f6598536b94cc1eecbc714a2c64', 'view': {'type': 'modal', 'title': {'type': 'plain_text', 'text': 'Workplace check-in'}, 'close': {'type': 'plain_text', 'text': 'Cancel'}, 'blocks': [{'type': 'section', 'text': {'type': 'plain_text', 'text': ':man-biking: Now loading...'}}]}, 'team_id': 'T049Y9BDDK5'}, headers: {'Content-Type': 'application/json;charset=utf-8', 'Authorization': '(redacted)', 'User-Agent': 'Python/3.10.1 slackclient/3.19.3 Windows/10'}
2022-11-21,14:43:02.418 DEBUG {thread_runner} [_debug_log_completion] Responding with status: 200 body: "" (22 millis)
2022-11-21,14:43:02.418 DEBUG {client} [send_message] Sending a message (session id: 65281e0b-5563-4b4e-93b9-e4fffd58200c, message: {"envelope_id": "8bfbc62c-5d2e-4820-b0e7-058f667c77ff"})
2022-11-21,14:43:02.418 DEBUG {internals} [send_response] Response time: 24 milliseconds
2022-11-21,14:43:02.419 DEBUG {client} [run_message_listeners] Message processing completed (type: interactive, envelope_id: 8bfbc62c-5d2e-4820-b0e7-058f667c77ff)
2022-11-21,14:43:02.674 DEBUG {base_client} [_perform_urllib_http_request_internal] Received the following response - status: 200, headers: {'date': 'Mon, 21 Nov 2022 13:43:02 GMT', 'server': 'Apache', 'x-powered-by': 'HHVM/4.153.1', 'access-control-allow-origin': '*', 'referrer-policy': 'no-referrer', 'x-slack-backend': 'r', 'x-slack-unique-id': 'Y3uAZtDmwNEO-3ea7NZ27AAAEDo', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'x-oauth-scopes': 'chat:write,channels:history,commands,groups:history,mpim:history,im:history', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'x-slack-req-id': '5d61e161322072d7e3aa95419d9699d5', 'vary': 'Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '165', 'x-backend': 'main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-fvse', 'x-slack-shared-secret-outcome': 'no-match', 'via': 'envoy-www-iad-9xw3, envoy-edge-fra-7g88', 'x-edge-backend': 'envoy-www', 'x-slack-edge-shared-secret-outcome': 'no-match', 'connection': 'close', 'transfer-encoding': 'chunked'}, body: {"ok":true,"view":{"id":"V04BN59S8A2","team_id":"T049Y9BDDK5","type":"modal","blocks":[{"type":"section","block_id":"z+K","text":{"type":"plain_text","text":":man-biking: Now loading...","emoji":true}}],"private_metadata":"","callback_id":"","state":{"values":{}},"hash":"1669038182.2vXz22eI","title":{"type":"plain_text","text":"Workplace check-in","emoji":true},"clear_on_close":false,"notify_on_close":false,"close":{"type":"plain_text","text":"Cancel","emoji":true},"submit":null,"previous_view_id":null,"root_view_id":"V04BN59S8A2","app_id":"A04BLLTH733","external_id":"","app_installed_team_id":"T049Y9BDDK5","bot_id":"B04B1DVDV54"}}
2022-11-21,14:43:02.675 ERROR {listener_error_handler} [handle] Failed to run listener function (error: 'view')
Traceback (most recent call last):
  File "C:\Users\LUCA\lib\site-packages\slack_bolt\listener\thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "C:\Users\LUCA\lib\site-packages\slack_bolt\listener\custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "c:\Users\LUCA\Desktop\LM\Bot\17.11\app.py", line 88, in open_modal_step1
    logger.info(body["view"]["state"]["values"])
KeyError: 'view'
```
and this is when trigger_id expires:

```
2022-11-21,14:43:09.771 DEBUG {client} [_on_message] on_message invoked: (message: {"envelope_id":"ab009adb-658c-46e8-928e-fd6a13cb8734","payload":{"type":"shortcut","token":"ZtSxK1RA3UTWN9tJ9TljKNhm","action_ts":"1669038186.950744","team":{"id":"T049Y9BDDK5","domain":"testincidento-aoi8763"},"user":{"id":"U04AN3EJ73J","username":"lucalocasto","team_id":"T049Y9BDDK5"},"is_enterprise_install":false,"enterprise":null,"callback_id":"open_incident_jira","trigger_id":"4405240214052.4338317455651.e7a76f0d016a023ee90d3541156ad223"},"type":"interactive","accepts_response_payload":false})
2022-11-21,14:43:09.771 DEBUG {client} [enqueue_message] A new message enqueued (current queue size: 1)
2022-11-21,14:43:09.771 DEBUG {client} [process_message] A message dequeued (current queue size: 0)
2022-11-21,14:43:09.772 DEBUG {client} [run_message_listeners] Message processing started (type: interactive, envelope_id: ab009adb-658c-46e8-928e-fd6a13cb8734)
2022-11-21,14:43:09.772 DEBUG {app} [dispatch] Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
2022-11-21,14:43:09.772 DEBUG {app} [dispatch] Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
2022-11-21,14:43:09.772 DEBUG {app} [dispatch] Applying slack_bolt.middleware.authorization.single_team_authorization.SingleTeamAuthorization
2022-11-21,14:43:09.772 DEBUG {app} [dispatch] Applying slack_bolt.middleware.ignoring_self_events.ignoring_self_events.IgnoringSelfEvents
2022-11-21,14:43:09.773 DEBUG {app} [dispatch] Applying slack_bolt.middleware.url_verification.url_verification.UrlVerification
2022-11-21,14:43:09.773 DEBUG {app} [dispatch] Checking listener: open_modal_step1 ...
2022-11-21,14:43:09.773 DEBUG {app} [dispatch] Running listener: open_modal_step1 ...
2022-11-21,14:43:09.773 DEBUG {base_client} [_urllib_api_call] Sending a request - url: https://www.slack.com/api/views.open, query_params: {}, body_params: {}, files: {}, json_body: {'trigger_id': '4405240214052.4338317455651.e7a76f0d016a023ee90d3541156ad223', 'view': {'type': 'modal', 'title': {'type': 'plain_text', 'text': 'Workplace check-in'}, 'close': {'type': 'plain_text', 'text': 'Cancel'}, 'blocks': [{'type': 'section', 'text': {'type': 'plain_text', 'text': ':man-biking: Now loading...'}}]}, 'team_id': 'T049Y9BDDK5'}, headers: {'Content-Type': 'application/json;charset=utf-8', 'Authorization': '(redacted)', 'User-Agent': 'Python/3.10.1 slackclient/3.19.3 Windows/10'}
2022-11-21,14:43:09.788 DEBUG {thread_runner} [_debug_log_completion] Responding with status: 200 body: "" (15 millis)
2022-11-21,14:43:09.788 DEBUG {client} [send_message] Sending a message (session id: 65281e0b-5563-4b4e-93b9-e4fffd58200c, message: {"envelope_id": "ab009adb-658c-46e8-928e-fd6a13cb8734"})
2022-11-21,14:43:09.788 DEBUG {internals} [send_response] Response time: 16 milliseconds
2022-11-21,14:43:09.788 DEBUG {client} [run_message_listeners] Message processing completed (type: interactive, envelope_id: ab009adb-658c-46e8-928e-fd6a13cb8734)
2022-11-21,14:43:10.030 DEBUG {base_client} [_perform_urllib_http_request_internal] Received the following response - status: 200, headers: {'date': 'Mon, 21 Nov 2022 13:43:10 GMT', 'server': 'Apache', 'x-powered-by': 'HHVM/4.153.1', 'access-control-allow-origin': '*', 'referrer-policy': 'no-referrer', 'x-slack-backend': 'r', 'x-slack-unique-id': 'Y3uAbgQqf0ntbrl0uxr2PQAAADk', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'access-control-allow-headers': 'slack-route, x-slack-version-ts, x-b3-traceid, x-b3-spanid, x-b3-parentspanid, x-b3-sampled, x-b3-flags', 'access-control-expose-headers': 'x-slack-req-id, retry-after', 'x-oauth-scopes': 'chat:write,channels:history,commands,groups:history,mpim:history,im:history', 'expires': 'Mon, 26 Jul 1997 05:00:00 GMT', 'cache-control': 'private, no-cache, no-store, must-revalidate', 'pragma': 'no-cache', 'x-xss-protection': '0', 'x-content-type-options': 'nosniff', 'x-slack-req-id': '64340bbf8cbfb1f26254e51e96d6b798', 'vary': 'Accept-Encoding', 'content-type': 'application/json; charset=utf-8', 'x-envoy-upstream-service-time': '128', 'x-backend': 'main_normal main_bedrock_normal_with_overflow main_canary_with_overflow main_bedrock_canary_with_overflow main_control_with_overflow main_bedrock_control_with_overflow', 'x-server': 'slack-www-hhvm-main-iad-xami', 'x-slack-shared-secret-outcome': 'no-match', 'via': 'envoy-www-iad-yxbl, envoy-edge-fra-67rq', 'x-edge-backend': 'envoy-www', 'x-slack-edge-shared-secret-outcome': 'no-match', 'connection': 'close', 'transfer-encoding': 'chunked'}, body: {"ok":false,"error":"expired_trigger_id"}
2022-11-21,14:43:10.031 ERROR {listener_error_handler} [handle] Failed to run listener function (error: The request to the Slack API failed. (url: https://www.slack.com/api/views.open)
The server responded with: {'ok': False, 'error': 'expired_trigger_id'})
Traceback (most recent call last):
  File "C:\Users\LUCA\lib\site-packages\slack_bolt\listener\thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "C:\Users\LUCA\lib\site-packages\slack_bolt\listener\custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "c:\Users\LUCA\Desktop\LM\Bot\17.11\app.py", line 87, in open_modal_step1
    res = client.views_open(trigger_id=body["trigger_id"], view=loading_modal)
  File "C:\Users\LUCA\lib\site-packages\slack_sdk\web\client.py", line 4454, in views_open
    return self.api_call("views.open", json=kwargs)
  File "C:\Users\LUCA\lib\site-packages\slack_sdk\web\base_client.py", line 156, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "C:\Users\LUCA\lib\site-packages\slack_sdk\web\base_client.py", line 187, in _sync_send
    return self._urllib_api_call(
  File "C:\Users\LUCA\lib\site-packages\slack_sdk\web\base_client.py", line 317, in _urllib_api_call
    ).validate()
  File "C:\Users\LUCA\lib\site-packages\slack_sdk\web\slack_response.py", line 199, in validate
    raise e.SlackApiError(message=msg, response=self)
slack_sdk.errors.SlackApiError: The request to the Slack API failed. (url: https://www.slack.com/api/views.open)
The server responded with: {'ok': False, 'error': 'expired_trigger_id'}
```

#### The `slack_bolt` version

installed slack-0.0.2

#### Python runtime version

Python 3.10.1

#### OS info

Microsoft Windows [Versione 10.0.19044.2251]

### Entire Code.

```python
import logging
import os
from datetime import datetime

from slack_bolt import App, Ack
from slack_sdk import WebClient
from slack_bolt.adapter.socket_mode import SocketModeHandler

logging.basicConfig(
    format="%(asctime)s.%(msecs)03d %(levelname)s {%(module)s} [%(funcName)s] %(message)s",
    datefmt="%Y-%m-%d,%H:%M:%S",
    level=logging.DEBUG,
    filename="log.log",
)

app = App(
    token=os.environ.get("SLACK_BOT_TOKEN"),
)
true = True


loading_modal = {
    "type": "modal",
    "title": {"type": "plain_text", "text": "Workplace check-in"},
    "close": {"type": "plain_text", "text": "Cancel"},
    "blocks": [
        {
            "type": "section",
            "text": {"type": "plain_text", "text": ":man-biking: Now loading..."},
        }
    ],
}


step1_modal = {
    "type": "modal",
    "callback_id": "open_incident",
    "title": {"type": "plain_text", "text": "Open an Incident"},
    "close": {"type": "plain_text", "text": "Close"},
    "submit": {"type": "plain_text", "text": "Submit"},
    "blocks": [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "Open an Incident on JIRA",
            },
        },
        {
            "type": "input",
            "block_id": "summary_description",
            "element": {
                "type": "plain_text_input",
                "action_id": "summary_input-action",
            },
            "label": {
                "type": "plain_text",
                "text": "Summary",
            },
        },
        {
            "type": "input",
            "block_id": "impact_description",
            "element": {
                "type": "plain_text_input",
                "multiline": true,
                "action_id": "impact_input-action",
            },
            "label": {
                "type": "plain_text",
                "text": "Description of Impact",
                "emoji": true,
            },
        },
    ],
}

# @app.shortcut("open_incident_jira")
@app.shortcut("open_incident_jira")
def open_modal_step1(ack: Ack, body: dict, client: WebClient, logger):
    ack()
    res = client.views_open(trigger_id=body["trigger_id"], view=loading_modal)
    logger.info(body["view"]["state"]["values"])
    logger.warning(body["view"]["state"]["values"])
    logger.error(body["view"]["state"]["values"])


"""def open_modal_step1(ack: Ack, body: dict, client: WebClient):
    ack()
    res2 = client.views_update(view_id=body["view"]["id"], hash=body["view"]["hash"], view=step1_modal)
"""


@app.view("open_incident")
def view_submission(ack, body, logger, view, say):
    ack()
    logger.info(body["view"]["state"]["values"])

    summaryDescription = view["state"]["values"]["summary_description"][
        "summary_input-action"
    ]["value"]
    user_id = body["user"]["id"]
    channel_id = body["channel"]["id"]

    # channel_id = body["channel"]["id"]
    logger.info(user_id)
    say(
        channel=channel_id,
        text=f"<@{user_id}> opened an Incident, summary: {summaryDescription}",
    )


# Start your app
if __name__ == "__main__":
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).start()
```

### Expected result:

It should open a modal, but sometimes it doesn't open a modal and trigger_id expires.

I tried to follow tips here:

https://github.com/slackapi/node-slack-sdk/issues/1131

but modal doesn't always pop, sometimes it does and sometimes it doesnt.

### Actual result:

Modal doesn't always pop, sometimes it does and sometimes it doesnt.

Using /slash commands the modal opens super fast, instead using shortcut it goes really slow (i think caused by UX?).

Is there anything else i can do or there is some kind of margin of error and it's a normal behavior?

Thanks!

Regards.

Requirements (place an x in each of the [ ])
[x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
[x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
[x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
Hi @lucafx, thanks for asking the question!

>Using /slash commands the modal opens super fast, instead using shortcut it goes really slow (i think caused by UX?).

We've never heard of this since the beginning of the global shortcuts.

With given information, I cannot guess the exact reason why your app fails to open a modal quickly with a global shortcut but the cause of the situation is that your app didn't use the trigger_id within three seconds. Possible causes are:
* Your app is intermittently unstable to respond
* There is some issue on the network connections between your app and Slack (specifically with WebSocket connections for Socket Mode)
* Outage or performance issues on the Slack side, but I don't think this can happen as you describe

To narrow down your issue, I would suggest trying to run the app in a different environment such as different wi-fi, another machine, on some cloud services, and so on. Hope you'll figure out the cause!

**Comment by lucafx** [comment]
Thank you @seratch ! 

I will try to make some test from a differente env!

Thank you!
Luca
