### ISSUE TITLE
POST request received but @app.event(message.channels) not called

### ISSUE THREAD

**Issue by marcocapano** [slackapi/bolt-python#790]
Hi there!
When I send a message on a channelI, I receive the post request (`127.0.0.1 - - [15/Dec/2022 17:19:31] "POST /slack/events HTTP/1.1" 200 -`) but `@app.event("message.channels")` is not invoked.

The bot is in the channel and I'm subscribed to `message.channels` as well (see image below)
Should I be using another event type to listen to new messages in the channel?

<img width="653" alt="Screenshot 2022-12-15 at 17 23 12" src="https://user-images.githubusercontent.com/23129028/207914265-40739539-4e8c-4576-8807-9b3927c341a0.png">

Code as following:

```python
import os
from pathlib import Path
from dotenv import load_dotenv
from slack_bolt import App
import logging

# logger in a global context
# requires importing logging
logging.basicConfig(level=logging.DEBUG)

env_path = Path('maestro-bot')/'.env'
load_dotenv(dotenv_path=env_path)

# Initializes your app with your bot token and signing secret
app = App(
    token=os.environ['SLACK_TOKEN'],
    signing_secret=os.environ['SIGNING_SECRET']
)

@app.event("message.channels")
def handle_message(payload, say, logger, context):
    event = payload.get('event', {})
    user_id = event.get('user')
    bot_id = context.get('botId')
    text = event.get('text')  

    logger.debug(payload)
    say(text)

# Start your app
if __name__ == "__main__":
    app.start(port=2000)
```

### Reproducible in:

```bash
pip freeze | grep slack
python --version
sw_vers && uname -v # or `ver`
```

#### The `slack_bolt` version
(Paste the output of `pip freeze | grep slack`)
```
slack-bolt==1.16.0
slack-sdk==3.19.5
slackclient==2.9.4
slackeventsapi==3.0.1
```

#### Python runtime version
(Paste the output of `python --version`)
`Python 3.9.6`

#### OS info
(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)
```
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
```

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. Send a message on the channel

### Expected result:
`def handle_message(payload, say, logger, context):` should get called, the message received should be posted again by the bot.

### Actual result:
While I can see in the terminal that I'm receiving a post request, the handler is not called.

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by srajiang** [comment]
Hey @marcocapano. Thanks for writing in!The way to get your callback working on message events in channel is to use the `@app.message` decorator. More on that here: https://slack.dev/bolt-python/concepts#message-listening

I tried reproducing your scenario just now without the decorator and just as a method, and got this related error: 
```
Traceback (most recent call last):
  File "/Users/sarah.jiang/dev/slack-cli/affectionate-mink-20/app.py", line 15, in <module>
    register_listeners(app)
  File "/Users/sarah.jiang/dev/slack-cli/affectionate-mink-20/listeners/__init__.py", line 13, in register_listeners
    events.register(app)
  File "/Users/sarah.jiang/dev/slack-cli/affectionate-mink-20/listeners/events/__init__.py", line 8, in register
    app.event("message.channels")(message_channels_callback)
  File "/Users/sarah.jiang/dev/slack-cli/affectionate-mink-20/.venv/lib/python3.10/site-packages/slack_bolt/app/app.py", line 737, in __call__
    primary_matcher = builtin_matchers.event(event, base_logger=self._base_logger)
  File "/Users/sarah.jiang/dev/slack-cli/affectionate-mink-20/.venv/lib/python3.10/site-packages/slack_bolt/listener_matcher/builtins.py", line 98, in event
    _verify_message_event_type(event_type)
  File "/Users/sarah.jiang/dev/slack-cli/affectionate-mink-20/.venv/lib/python3.10/site-packages/slack_bolt/listener_matcher/builtins.py", line 176, in _verify_message_event_type
    raise ValueError(error_message_event_type(event_type))
ValueError: Although the document mentions "message.channels", it is not a valid event type. Use "message" instead. If you want to filter message events, you can use `event.channel_type` for it.
```

**Comment by marcocapano** [comment]
@srajiang is it possible that I should subscribe to some other event?
currently I only subscribe to `message.channels` (scope `channels:history`)

**Comment by srajiang** [comment]
Ah my mistake, I think that @app.message is more helpful when you're trying to filter on specific message content (say with regex). Try using @app.event("message") in your decorator.

And then I think for scopes, you app needs the scopes from here: 

https://api.slack.com/events/message 

Adding all 4 scopes would give your app permissions to get message events from public channels, ims, dms, groups that your app is a member of.

**Comment by marcocapano** [comment]
Thanks for the help so far @srajiang 🙏🏻
I think we're almost there 😆

I've updated the scopes and now when a message is received I can see that slack sends something to my bot, but I get this in the logs:

```
127.0.0.1 - - [16/Dec/2022 10:29:42] "POST /slack/events HTTP/1.1" 404 -
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.ssl_check.ssl_check.SslCheck
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.request_verification.request_verification.RequestVerification
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.authorization.single_team_authorization.SingleTeamAuthorization
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.ignoring_self_events.ignoring_self_events.IgnoringSelfEvents
DEBUG:slack_bolt.App:Applying slack_bolt.middleware.url_verification.url_verification.UrlVerification
WARNING:slack_bolt.App:Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)
```

The funny this is though, I am doing exactly what the logs are suggesting 😅
Here is my code:

```python
import os
from pathlib import Path
from dotenv import load_dotenv
from slack_bolt import App
import logging

# logger in a global context
# requires importing logging
logging.basicConfig(level=logging.DEBUG)

env_path = Path('maestro-bot')/'.env'
load_dotenv(dotenv_path=env_path)

# Initializes your app with your bot token and signing secret
app = App(
    token=os.environ['SLACK_TOKEN'],
    signing_secret=os.environ['SIGNING_SECRET']
)

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)

# Start your app
if __name__ == "__main__":
    app.start(port=2000)
```

**Comment by makototamopeva** [comment]
Hi @srajiang I have the similar issue. 

Here is my code. 
```
import os
from slack_bolt import App
from dotenv import load_dotenv
load_dotenv()

SIGNING_SECRET = os.environ['SIGNING_SECRET']
SLACK_BOT_TOKEN = os.environ['SLACK_BOT_TOKEN']

# Initialize your app with your bot token and signing secret
app = App(
    token=SLACK_BOT_TOKEN,
    signing_secret=SIGNING_SECRET
)

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)
```

When I write a message on the private channel that this bot joined, I see this error message:
```
127.0.0.1 - - [22/Feb/2024 22:19:14] "POST /slack/events HTTP/1.1" 404 -
Unhandled request ({'type': 'event_callback', 'event': {'type': 'message'}})
---
[Suggestion] You can handle this type of event with the following listener function:

@app.event("message")
def handle_message_events(body, logger):
    logger.info(body)
```

I get the same error message with `@app.message()` as well. I followed [this tutorial](https://slack.dev/bolt-python/tutorial/getting-started) but didn't work.
```
@app.message("hello")
def message_hello(message, say):
    say(f"Hey there <@{message['user']}>!")
```

The example in [this tutorial](https://api.slack.com/start/building/bolt-python) uses @app.event("app_home_opened") and it works. But what I really want is that the bot responds to some messages in the public/private channel. 

Here are the events that this app is subscribed to:
<img width="653" alt="Screenshot 2024-02-22 at 23 25 04" src="https://github.com/slackapi/bolt-python/assets/154126564/be9c9c87-0ce9-4399-bbc2-f90cc3a21410">

Versions:
Python: 3.9.6
slack_bolt: 1.18.1
slack-sdk: 3.27.0
slackclient: 2.9.4
slackeventsapi: 3.0.1

OS: Ubuntu 22.04.3 LTS

**Comment by BigtreeHsieh** [comment]
I have similar issue here and finally found out the solution.
I tried to add **message.im** to **Subscribe to bot events**, then save the chage.
Thus I can receive event when direct message to my bot.
![Slack_BOT_Setting](https://github.com/slackapi/bolt-python/assets/9245266/9cc5001a-d9b8-40d1-b630-cdf696280e81)
