### ISSUE TITLE
AWS Lambda SlackRequestHandler: Support for serverless offline

### ISSUE THREAD

**Issue by asontha** [slackapi/bolt-python#813]
Trying to use `serverless` so that I can use a consistent tool to run locally and deploy. However, it looks like `boto3`  the SlackRequestHandler can't handle using the fake function it sets up.

#### The `slack_bolt` version

slack-bolt==1.16.1
slack-sdk==3.19.5

#### Python runtime version

Python 3.10.9

#### OS info

ProductName:    macOS
ProductVersion: 12.5
BuildVersion:   21G72
Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:22 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T6000
#### Steps to reproduce:

`serverless.yml`
```
service: test-project
 
provider:
  name: aws
  runtime: python3.9
 
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
```

### Expected result:

Able to invoke offline lambda function

### Actual result:

```
ERROR:slack_bolt.App:Failed to run a middleware (error: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-east-1:451671465928:function:serverless:Fake)
Traceback (most recent call last):
  File "<PROJECT_FOLDER>/.venv/lib/python3.10/site-packages/slack_bolt/app/app.py", line 523, in dispatch
    listener_response: Optional[BoltResponse] = self._listener_runner.run(
  File "<PROJECT_FOLDER>/.venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 98, in run
    self._start_lazy_function(lazy_func, request)
  File "<PROJECT_FOLDER>/.venv/lib/python3.10/site-packages/slack_bolt/listener/thread_runner.py", line 186, in _start_lazy_function
    self.lazy_listener_runner.start(function=lazy_func, request=copied_request)
  File "<PROJECT_FOLDER>/.venv/lib/python3.10/site-packages/slack_bolt/adapter/aws_lambda/lazy_listener_runner.py", line 25, in start
    invocation = self.lambda_client.invoke(
  File "<PROJECT_FOLDER>/.venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "<PROJECT_FOLDER>/.venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the Invoke operation: Function not found: arn:aws:lambda:us-east-1:451671465928:function:serverless:Fake
```

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by asontha** [comment]
Looks like this happens once deployed too:
```


[ERROR]	2023-01-28T20:21:33.907Z	64522506-4f9e-4991-9d7a-2dcd4e266733	Failed to run a middleware (error: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::451671465928:assumed-role/slack-bot-dev-us-east-1-lambdaRole/slack-bot-dev-slack is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:451671465928:function:slack-bot-dev-slack because no identity-based policy allows the lambda:InvokeFunction action)Traceback (most recent call last):  File "/var/task/slack_bolt/app/app.py", line 523, in dispatch    listener_response: Optional[BoltResponse] = self._listener_runner.run(  File "/var/task/slack_bolt/listener/thread_runner.py", line 98, in run    self._start_lazy_function(lazy_func, request)  File "/var/task/slack_bolt/listener/thread_runner.py", line 186, in _start_lazy_function    self.lazy_listener_runner.start(function=lazy_func, request=copied_request)  File "/var/task/slack_bolt/adapter/aws_lambda/lazy_listener_runner.py", line 25, in start    invocation = self.lambda_client.invoke(  File "/var/runtime/botocore/client.py", line 391, in _api_call    return self._make_api_call(operation_name, kwargs)  File "/var/runtime/botocore/client.py", line 719, in _make_api_call    raise error_class(parsed_response, operation_name)botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::451671465928:assumed-role/slack-bot-dev-us-east-1-lambdaRole/slack-bot-dev-slack is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:451671465928:function:slack-bot-dev-slack because no identity-based policy allows the lambda:InvokeFunction action | [ERROR] 2023-01-28T20:21:33.907Z 64522506-4f9e-4991-9d7a-2dcd4e266733 Failed to run a middleware (error: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::451671465928:assumed-role/slack-bot-dev-us-east-1-lambdaRole/slack-bot-dev-slack is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:451671465928:function:slack-bot-dev-slack because no identity-based policy allows the lambda:InvokeFunction action) Traceback (most recent call last): File "/var/task/slack_bolt/app/app.py", line 523, in dispatch listener_response: Optional[BoltResponse] = self._listener_runner.run( File "/var/task/slack_bolt/listener/thread_runner.py", line 98, in run self._start_lazy_function(lazy_func, request) File "/var/task/slack_bolt/listener/thread_runner.py", line 186, in _start_lazy_function self.lazy_listener_runner.start(function=lazy_func, request=copied_request) File "/var/task/slack_bolt/adapter/aws_lambda/lazy_listener_runner.py", line 25, in start invocation = self.lambda_client.invoke( File "/var/runtime/botocore/client.py", line 391, in _api_call return self._make_api_call(operation_name, kwargs) File "/var/runtime/botocore/client.py", line 719, in _make_api_call raise error_class(parsed_response, operation_name) botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::451671465928:assumed-role/slack-bot-dev-us-east-1-lambdaRole/slack-bot-dev-slack is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:us-east-1:451671465928:function:slack-bot-dev-slack because no identity-based policy allows the lambda:InvokeFunction action
-- | --
```

**Comment by seratch** [comment]
Hi @asontha, thanks for writing in! We've explored possible ways to make this feasible in the past, but we concluded there is no simple way to do so. 

So, for local development, I recommend using `app.start()`, Flask adapter, or Socket Mode instead. Verifying your `App`'s behavior with a different adapter is not a problem at all as `App` itself is completely adapter-agnostic. Perhaps, Socket Mode should be the easiest. Having three source files like below and running `local_dev.py` for local development would be a good way to go.

* `app.py`, which provides `App` instance
* `handler.py`, which runs the `App` (you can import it like `from app import app`) on your AWS Lamdba production environment
* `local_dev.py`, which runs Socket Mode adapter with imported `App` instance

I hope this helps.

**Comment by seratch** [comment]
@asontha 
>error: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::451671465928:assumed-role/slack-bot-dev-us-east-1-lambdaRole/slack-bot-dev-slack is not authorized to perform: lambda:InvokeFunction

This production error is due to a lack of permission. As mentioned in the example config:
https://github.com/slackapi/bolt-python/blob/v1.16.1/examples/aws_lambda/lazy_aws_lambda_config.yaml#L8 , you need to have lambda:InvokeFunction & lambda:GetFunction permissions for it.

As for the prod app, adding these permissions should resolve your issue. However, it still does not properly work for local dev. So, using a different adapter for local dev is recommended regardless of the permission issue.

**Comment by asontha** [comment]
Hmmmm, but shouldn't `serverless deploy` be pulling from my CLI credentials? That should have full access.

**Comment by seratch** [comment]
Yes, for your local credentials. However, as the AWS error indicates, your Lambda function works with its associated IAM role. You need to add the two permissions to the role.

**Comment by asontha** [comment]
Hmmmm, but it looks like it's configured to have that no?

![image](https://user-images.githubusercontent.com/67022327/215290272-a4cc9789-7ff1-4623-add9-1ae8aa261d8e.png)

**Comment by asontha** [comment]
Nevermind I was looking at the wrong place. It looks like I need to configure the specific function role and I should be able to do this with `serverless.yml`

**Comment by asontha** [comment]
For your records, here's a working `serverless.yml`

```
service: slack-bot
 
provider:
  name: aws
  timeout: 30
  runtime: python3.9
  iam:
    role:
      managedPolicies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
 
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
```

Can probably remove the serverless-offline plugin.

**Comment by seratch** [comment]
Thanks for sharing your knowledge! Let me close this issue now.
