### ISSUE TITLE
Cannot pass thread_ts to `respond()` utility

### ISSUE THREAD

**Issue by athlindemark** [slackapi/bolt-python#842]
(Filling out the following details about bugs will help us solve your issue sooner.)

### Reproducible in:

```python
@app.command("/create_blocks")
def create_blocks(ack, body, respond):
    ack()
    respond(
        {
            "blocks": blocks,
            "response_type": "in_channel",
            "thread_ts": ts,
        }
    )
```

#### The `slack_bolt` version
slack-bolt==1.15.2
slack-sdk==3.19.2
(Paste the output of `pip freeze | grep slack`)

#### Python runtime version
❯ python --version
Python 3.9.1
(Paste the output of `python --version`)

#### OS info
Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64
(Paste the output of `sw_vers && uname -v` on macOS/Linux or `ver` on Windows OS)

#### Steps to reproduce:

(Share the commands to run, source code, and project settings (e.g., setup.py))

1. respond object from @app.command
2. tries to respond with
```python
respond(
    {
        "blocks": blocks,
        "response_type": "in_channel",
        "thread_ts": ts,
    }
)
```

3.

### Expected result:
Message gets sent
(Tell what you expected to happen)

### Actual result:
```
Failed to run listener function (error: _build_message() got an unexpected keyword argument 'thread_ts')
Traceback (most recent call last):
  File "/Users/anders/opt/anaconda3/envs/slack/lib/python3.8/site-packages/slack_bolt/listener/thread_runner.py", line 120, in run_ack_function_asynchronously
    listener.run_ack_function(request=request, response=response)
  File "/Users/anders/opt/anaconda3/envs/slack/lib/python3.8/site-packages/slack_bolt/listener/custom_listener.py", line 50, in run_ack_function
    return self.ack_function(
  File "/Users/anders/factiverse/facticat/apps/slack_bolt/app.py", line 300, in stance_detection
    stance_detection_channel(claim=claim, lang=lang, respond=respond, ts="0")
  File "/Users/anders/factiverse/facticat/apps/slack_bolt/microfacts_feedback/slack_bot.py", line 114, in stance_detection_channel
    sdf.post_stance(ts, respond)
  File "/Users/anders/factiverse/facticat/apps/slack_bolt/stance_detection/stance_detection.py", line 164, in post_stance
    self._post_stance_detection_messages(
  File "/Users/anders/factiverse/facticat/apps/slack_bolt/stance_detection/stance_detection.py", line 84, in _post_stance_detection_messages
    respond(
  File "/Users/anders/opt/anaconda3/envs/slack/lib/python3.8/site-packages/slack_bolt/context/respond/respond.py", line 59, in __call__
    message = _build_message(**text_or_whole_response)
TypeError: _build_message() got an unexpected keyword argument 'thread_ts'
```
(Tell what actually happened with logs, screenshots)

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
Hi @athlindemark, thanks for writing in! Unfortunately, `respond` utility (specifically, its underlying `response_url`) does not support replies in a thread. Please use `say()` or `client.chat_postMessage()` / `client.chat_postEphemeral()` instead.

**Comment by athlindemark** [comment]
Hi,Then you should probably update the docs not to include: ![image](https://user-images.githubusercontent.com/78022224/223408614-f0b14e11-bc32-4bec-9af1-ce222a01f601.png)
