### ISSUE TITLE
Make sure if `@app.message({"subtype": "message_changed"})` works

### ISSUE THREAD

**Issue by seratch** [slackapi/bolt-python#89]
* [ ] Add a sample
* [ ] Add unit tests for sync/async

https://github.com/slackapi/bolt-python/pull/78#discussion_r487343485

## Requirements

Please read the [Contributing guidelines](https://github.com/slackapi/bolt-python/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment]
@misscoded The pattern doesn't exist in Bolt JS document. Also, it doesn't work. Let's use another sample in the doc.

```javascript
app.message({"subtype": "message_changed"}, async ({ say }) => {
  await say("You've modified a message!");
})
```

```
[ERROR]  bolt-app { Error: middleware[toCallMiddlewareIndex] is not a function
    at Object.asCodedError (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/errors.js:22:12)
    at App.handleError (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/App.js:368:43)
    at App.processEvent (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/App.js:361:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'slack_bolt_unknown_error',
  original:
   TypeError: middleware[toCallMiddlewareIndex] is not a function
       at invokeMiddleware (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/middleware/process.js:13:53)
       at next (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/middleware/process.js:14:29)
       at Array.<anonymous> (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/middleware/builtin.js:218:15)
       at invokeMiddleware (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/middleware/process.js:13:53)
       at next (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/middleware/process.js:14:29)
       at Array.exports.onlyEvents (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/middleware/builtin.js:64:11)
       at invokeMiddleware (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/middleware/process.js:13:53)
       at Object.processMiddleware (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/middleware/process.js:23:12)
       at listenerResults.listeners.map (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/App.js:345:42)
       at Array.map (<anonymous>) }
(node:54938) UnhandledPromiseRejectionWarning: Error: middleware[toCallMiddlewareIndex] is not a function
    at Object.asCodedError (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/errors.js:22:12)
    at App.handleError (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/App.js:368:43)
    at App.processEvent (/Users/ksera/github/bolt-starter/node_modules/@slack/bolt/dist/App.js:361:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:54938) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

**Comment by anthonygualandri** [comment]
@seratch was this ever fixed / added or accomplished in another way? I'm still getting a similar error to the one above when I try the pattern suggested. I don't want to have to use a specific message pattern / text, but want to listen to all messages that are replies. Thanks!

**Comment by seratch** [comment]
@anthonygualandri Using a listener matcher is a recommended way for it. Refer to https://slack.dev/bolt-python/concepts#listener-middleware for details.

**Comment by anthonygualandri** [comment]
Got it. Thanks so much!
