### ISSUE TITLE
Default Test Case / Example Excepts

### ISSUE THREAD

**Issue by rbuck-som** [slackapi/bolt-python#964]
I have been trying to get slack bolt to shut down cleanly, unable to do so.

https://github.com/slackapi/bolt-python/blob/a3f4bae9d539c332fa395848b5710ae42ab1eb91/examples/socket_mode_async.py#L128

Copying the code above as a simple hello world example, shutting down with SIG INT results in an exception that I always see when running with asyncio:

```
Traceback (most recent call last):
  File "/Users/robert.buck/ws/workspaces/softeng-slack-bolt-library/src/project-template/src/slack_library_virtual_assistant/__main__.py", line 28, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
ERROR:asyncio:Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fc5a813e160>
transport: <_SelectorSocketTransport closing fd=11>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 908, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 914, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 709, in _fatal_error
    self._force_close(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 721, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc5f818e7c0>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc5f818e4f0>
```

How are we supposed to properly shut down? Can you provide an updated test case in your test suite that does not produce an error? Thank you!

**Comment by seratch** [comment]
Hi @rbuck-som, thanks for writing in. To avoid getting the error logs, you can incorporate the try/except/finally clauses as shown below:

```python
async def main():
    handler = AsyncSocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
    try:
        await handler.start_async()
    finally:
        await handler.close_async()

if __name__ == "__main__":
    import asyncio
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass  # or you can do anything I would like at this time
```

Regarding the `OSError: [Errno 9] Bad file descriptor` logs, the erorr may not always occur (at least it rarely arises for me). I hope this was helpful to you!
